name: Generate Release Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      klotho-tap:
        description: 'klotho homebrew tap repository'
        required: false
        default: 'KlothoPlatform/homebrew-tap'
jobs:
  generate:
    name: Generate Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0

      - name: Install Dependencies
        run: npm install

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          skip-tag: 'true'

      - name: Get the version
        id: get_version
        run: echo version=$(jq -r .version package.json) >> $GITHUB_OUTPUT

      - name: Build
        run: npm run package

      # Remove old release drafts by using the curl request for the available releases with draft flag
      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh api repos/{owner}/{repo}/releases \
            --jq '.[] | select(.draft == true) | .id' \
            | xargs -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}

      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: v${{ steps.get_version.outputs.version }}
          tag_name: v${{ steps.get_version.outputs.version }}
          files: ./klotho-*.vsix
          fail_on_unmatched_files: true
          generate_release_notes: true
